# fly.toml file generated for late-pond-230 on 2022-06-07T16:52:05+10:00

app = "late-pond-230"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  NODE_ENV="production"
  NEXT_PUBLIC_API_URL="https://retrobox.app/api"

[build]
  build-target = "runner"

[deploy]
  release_command = "yarn prisma:deploy"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
