name: Fly Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'apps/api/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build & Deploy
        run: yarn deploy:api --remote-only